version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  bot:
    build: .
    env_file: .env
    volumes:
      - ./config:/ditto/config
      - ./lib:/ditto/lib
      - ./mix.exs:/ditto/mix.exs
      - ./mix.lock:/ditto/mix.lock
      - ./test:/ditto/test
    depends_on:
      - redis
